package com.stoxsim.finwiz.service;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.Mockito.when;

import java.io.IOException;
import java.net.InetSocketAddress;
import java.nio.charset.StandardCharsets;
import java.time.Instant;
import java.util.concurrent.atomic.AtomicReference;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.web.server.ResponseStatusException;

import com.stoxsim.finwiz.api.FinwizRequest;
import com.stoxsim.finwiz.api.FinwizRequest.ExperienceLevel;
import com.stoxsim.finwiz.api.FinwizRequest.Topic;
import com.stoxsim.finwiz.config.FinwizProperties;
import com.stoxsim.finwiz.service.FinwizContextService.ContextSnapshot;
import com.sun.net.httpserver.HttpServer;

@ExtendWith(MockitoExtension.class)
class FinwizServiceTest {

    @Mock private FinwizContextService contexts;

    private HttpServer server;

    @AfterEach
    void stopServer() {
        if (server != null) {
            server.stop(0);
        }
    }

    @Test
    void usesEducationalFallbackWhenNoGeminiKeyIsConfigured() {
        FinwizProperties properties = new FinwizProperties();
        properties.setApiKey("");
        FinwizRequest request = new FinwizRequest(
            "Why can profit rise while operating cash flow falls?",
            Topic.CASH_FLOW,
            ExperienceLevel.BEGINNER,
            null,
            null,
            null
        );
        when(contexts.build(request)).thenReturn(ContextSnapshot.empty());

        var response = new FinwizService(properties, contexts).ask(request);

        assertThat(response.provider()).isEqualTo("STOXSIM_EDUCATIONAL_FALLBACK");
        assertThat(response.answer()).contains("Operating cash flow");
        assertThat(response.disclaimer()).contains("does not provide investment advice");
        assertThat(response.groundedInStoxSimData()).isFalse();
    }

    @Test
    void sendsGeminiThinkingBudgetAndReturnsGeneratedText() throws IOException {
        AtomicReference<String> receivedBody = new AtomicReference<>();
        AtomicReference<String> receivedKey = new AtomicReference<>();
        server = HttpServer.create(new InetSocketAddress("127.0.0.1", 0), 0);
        server.createContext("/v1beta/models/gemini-2.5-flash:generateContent", exchange -> {
            receivedKey.set(exchange.getRequestHeaders().getFirst("x-goog-api-key"));
            receivedBody.set(new String(exchange.getRequestBody().readAllBytes(), StandardCharsets.UTF_8));
            byte[] payload = """
                {"candidates":[{"content":{"parts":[{"text":"Operating cash flow is the cash generated by normal business operations."}]},"finishReason":"STOP"}]}
                """.getBytes(StandardCharsets.UTF_8);
            exchange.getResponseHeaders().set("Content-Type", "application/json");
            exchange.sendResponseHeaders(200, payload.length);
            exchange.getResponseBody().write(payload);
            exchange.close();
        });
        server.start();

        FinwizProperties properties = new FinwizProperties();
        properties.setApiKey("test-gemini-key");
        properties.setBaseUrl("http://127.0.0.1:" + server.getAddress().getPort());
        properties.setThinkingBudget(0);
        FinwizRequest request = new FinwizRequest(
            "Explain operating cash flow.",
            Topic.CASH_FLOW,
            ExperienceLevel.BEGINNER,
            null,
            null,
            null
        );
        when(contexts.build(request)).thenReturn(ContextSnapshot.empty());

        var response = new FinwizService(properties, contexts).ask(request);

        assertThat(response.provider()).isEqualTo("GEMINI");
        assertThat(response.model()).isEqualTo("gemini-2.5-flash");
        assertThat(response.answer()).contains("cash generated by normal business operations");
        assertThat(receivedKey.get()).isEqualTo("test-gemini-key");
        assertThat(receivedBody.get()).contains("\"thinkingBudget\":0");
    }

    @Test
    void preservesVerifiedContextInFallbackMode() {
        FinwizProperties properties = new FinwizProperties();
        FinwizRequest request = new FinwizRequest(
            "Explain the available data without recommending a trade.",
            Topic.STOCK_FUNDAMENTALS,
            ExperienceLevel.BEGINNER,
            null,
            null,
            null
        );
        var context = new ContextSnapshot(
            true,
            "TEST",
            Instant.parse("2026-08-01T12:00:00Z"),
            "Quote: lastPrice=100.00, previousClose=98.00."
        );
        when(contexts.build(request)).thenReturn(context);

        var response = new FinwizService(properties, contexts).ask(request);

        assertThat(response.answer()).contains("What the verified StoxSim data says");
        assertThat(response.answer()).contains("lastPrice=100.00");
        assertThat(response.dataAsOf()).isEqualTo(context.dataAsOf());
    }

    @Test
    void rejectsQuestionsAboveTheConfiguredLimit() {
        FinwizProperties properties = new FinwizProperties();
        properties.setMaxQuestionCharacters(10);
        FinwizRequest request = new FinwizRequest(
            "This question is longer than ten characters.",
            Topic.LEARN,
            ExperienceLevel.BEGINNER,
            null,
            null,
            null
        );

        assertThatThrownBy(() -> new FinwizService(properties, contexts).ask(request))
            .isInstanceOf(ResponseStatusException.class)
            .hasMessageContaining("Question is too long");
    }
}
